### ISSUE TITLE
Page loads are way longer than it should be

### ISSUE THREAD

**Issue by paales** [ho-nl/docker-development-box#16]
- Vanmoof 12s vs 3s on configurator page.
- Waardijk ~3s vs 1.5s on category page.

**Comment by NickdeK** [comment]
https://github.com/ho-nl/docker-development-box/commit/838b98a183da2f2c1fa85e12aa17e9aceadfaab4 Reduced the configurator page load to 7 seconds.

**Comment by paales** [comment]
Again improves performance: https://github.com/ho-nl/docker-development-box/commit/d260ef56ec45468d4f492590b02f866dffd042ca by a second

**Comment by paales** [comment]
Latest release: From: `5.34s 4.81s 4.37s 4.72s` to `3.68s 4.26s 3.98s 3.69s 3,73s 4,01s`
https://github.com/ho-nl/docker-development-box/issues/10#issuecomment-639384629

**Comment by paales** [comment]
MySQL performance is tracked in #23
