### ISSUE TITLE
Install PHP extensions

### ISSUE THREAD

**Issue by paales** [ho-nl/docker-development-box#27]
It seems we're missing the php intl extension

Check which extension are required with Magento and install them as well.

**Comment by PascalBrouwers** [comment]
Coincidentally I was already looking at this page:
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html
ext-bcmath
ext-ctype
ext-curl
ext-dom
ext-gd
ext-hash
ext-iconv
ext-intl
ext-mbstring
ext-openssl
ext-pdo_mysql
ext-simplexml
ext-soap
ext-sockets
ext-xsl
ext-zip
lib-libxml

**Comment by paales** [comment]
I think we've got the following:

- [x] ext-bcmath
- [x] ext-ctype
- [x] ext-curl
- [x] ext-dom
- [x] ext-gd
- [x] ext-hash
- [x] ext-iconv
- [ ] ext-intl
- [x] ext-mbstring
- [x] ext-openssl
- [x] ext-pdo_mysql
- [x] ext-simplexml (xml, xmlreader, xmlrpc, xmlwriter)
- [x] ext-soap
- [x] ext-sockets
- [x] ext-xsl
- [x] ext-zip (zlib)
- [x] lib-libxml (xml, xmlreader, xmlrpc, xmlwriter)

**Comment by paales** [comment]
>  facebook/webdriver 1.7.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.

**Comment by paales** [comment]
It turned out that I had to use php 7.2 instead of 7.3, what the project expected, now I don't get any errors. If I check the above list again I get:

- [x] ext-bcmath
- [x] ext-ctype
- [x] ext-curl
- [x] ext-dom
- [x] ext-gd
- [x] ext-hash
- [x] ext-iconv
- [x] ext-intl
- [x] ext-mbstring
- [x] ext-openssl
- [x] ext-pdo_mysql
- [x] ext-simplexml (xml, xmlreader, xmlrpc, xmlwriter)
- [x] ext-soap
- [x] ext-sockets
- [x] ext-xsl
- [x] ext-zip
- [x] lib-libxml
