### ISSUE TITLE
Creating local mounts throws error when multiple projects are using the same folder structure

### ISSUE THREAD

**Issue by Billydg** [ho-nl/docker-development-box#28]
Project 1:
Sightful/src
Project 2:
Foreyes/src

All of the project files are located in the src folder which causes the local mounts to be prefixed with "src_" . This means that multiple projects will have to use the same src_mysql-mount and src_nginx_mount. You will have to manually remove the mounts from project 1 to start project 2.

When running `docker-compose up`

`Creating volume "src_nginx-mount" with local driver
ERROR: Configuration for volume mysql-mount specifies "device" driver_opt :/Users/billydegraaf/Sites/foreyes/src/var/.mysqldata, but a volume with the same name uses a different "device" driver_opt (:/Users/billydegraaf/Sites/Sightful/src/var/.mysqldata). If you wish to use the new configuration, please remove the existing volume "src_mysql-mount" first:
$ docker volume rm src_mysql-mount`

**Comment by PascalBrouwers** [comment]
Ah ja, goeie. Misschien in de readme duidelijk neerzetten dat de folder structuur van je project dus aangepast moet worden?

**Comment by paales** [comment]
Gezien dit een legacy transition is en iedereen dit inmiddels wel weet laat ik dit enkel als Github issue staan. Als mensen zoeken naar dit probleem komen ze het vanzelf tegen.
