### ISSUE TITLE
Mysql cannot mount with default docker-compose.yml

### ISSUE THREAD

**Issue by Billydg** [ho-nl/docker-development-box#29]
```docker-compose up -d

Creating src_mysql_1 ... error

ERROR: for src_mysql_1  Cannot start service mysql: error while mounting volume '/var/lib/docker/volumes/src_mysql-mount/_data': failed to mount local volume: mount :/Users/billydegraaf/Sites/foreyes/src/var/.mysqldata:/var/lib/docker/volumes/src_mysql-mount/_data, data: addr=192.168.65.2,nolock,hard,nointr,nfsvers=3: no such file or directory

ERROR: for mysql  Cannot start service mysql: error while mounting volume '/var/lib/docker/volumes/src_mysql-mount/_data': failed to mount local volume: mount :/Users/billydegraaf/Sites/foreyes/src/var/.mysqldata:/var/lib/docker/volumes/src_mysql-mount/_data, data: addr=192.168.65.2,nolock,hard,nointr,nfsvers=3: no such file or directory
ERROR: Encountered errors while bringing up the project.```

**Comment by wimvdputten** [comment]
Er is een work around voor deze bug.

De container wilt niet runnen omdat de map/link nog niet bestaat, dit kunnen we oplossen door tijdelijk de mount link aan te passen.
 

`  mysql:
    image: percona:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - ./vendor/reach-digital/docker-devbox/mysql:/etc/my.cnf.d
      - mysql-mount:/var/lib/mysql`

Door de volume "mysql-mount" te veranderen naar "./var/.mysqldata"

`  mysql:
    image: percona:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - ./vendor/reach-digital/docker-devbox/mysql:/etc/my.cnf.d
      - ./var/.mysqldata:/var/lib/mysql`

Als "docker-compose up -d" nu wel draait kunnen we container "docker-compose down" gebruiken en de mount weer terug veranderen. 

Docker-compose zou nu moeten werken

**Comment by NickdeK** [comment]
```bash
│   Initializing database                                                                                                                                                         │
│   2020-09-02T13:59:28.907625-00:00 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be mer   │
│   ged with strict mode in a future release.                                                                                                                                     │
│   2020-09-02T13:59:28.911580-00:00 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.                                                           │
│   2020-09-02T13:59:28.911665-00:00 0 [ERROR] Aborting                                                                                                                           │
│   2020-09-02T13:59:28.912768700Z
```
Using this right now causes the above error because `var/.mysqldata/README.md` exists.

Workaround: change `- mysql-mount:/var/lib/mysql` to `- ./var/.mysqldata:/var/lib/mysql` in the `docker-compose.yml` file.

**Comment by paales** [comment]
Jeroen heeft denk enkel gecheckt voor ElasticSearch.

Er moeten files in staan om een NFS mount te kunnen maken, maar mogen voor MySQL dus geen files in staan om op te starten. Handy dandy. Misschien dus de data directory leeg gooien voordat MySQL start, maar nadat de NFS mount is aangemaakt..

**Comment by paales** [comment]
@NickdeK Zou nu gefixt moeten zijn

**Comment by paales** [comment]
@NickdeK Nog kunnen controleren of het nu werkt?

**Comment by Maikel-Koek** [comment]
@paales Ik probeer 12Go M2 te updaten naar 206, maar hou nog steeds MySQL problemen, moet ik nog iets meer doen dan alleen maar package updaten en opnieuw opstarten?

![Schermafbeelding 2020-10-01 om 11 09 04](https://user-images.githubusercontent.com/6301809/94790417-8be72c80-03d6-11eb-98bb-99eec6136d62.png)

```
( ! ) Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /Users/maikelkoek/Sites/project-12gobiking-m2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php on line 144
```

**Comment by paales** [comment]
@Maikel-Koek De issues welke jij omschrijft heeft niets te maken met de mount zelf, laten we even een nieuw issue aanmaken. Wat jij omschrijft is nieuw voor mij namelijk.
