### ISSUE TITLE
Xdebug not working for PHP7.2

### ISSUE THREAD

**Issue by PascalBrouwers** [ho-nl/docker-development-box#33]
Xdebug not working for PHP7.2. Have to use Xdebug 2.7.0alpha1

**Comment by paales** [comment]
Running install again didn't solve the issue? https://github.com/ho-nl/docker-development-box/releases/tag/v2.0.2

**Comment by PascalBrouwers** [comment]
Nope, but it might also be my version of phpstorm.

**Comment by paales** [comment]
Determined that it is PHPStorm
