### ISSUE TITLE
Keep using Magento 2.3 on 3.0.0 branch

### ISSUE THREAD

**Issue by PascalBrouwers** [ho-nl/docker-development-box#48]
go to your mysql container using `ctop` (exec shell) and run:
```
mysql -uroot -pmagento

ALTER USER magento IDENTIFIED WITH 'mysql_native_password' BY 'magento';
SET PERSIST log_bin_trust_function_creators=1;
GRANT ALL ON *.* TO 'magento'@'%';
```

Change in docker-compose.yml: 
```
FPM_PORT: 9074
FPM_XDEBUG: 9174
```

to:
```
FPM_PORT: 9072
FPM_XDEBUG: 9172
```

Switch php back to php 7.2 for cli
```
brew unlink php@7.4
brew link php@7.2 --force
```

restart docker:
`docker-compose down && docker-compose up -d`

**Comment by PascalBrouwers** [comment]
@paales moet ik dit ook in de readme verwerken?
Hiermee kan je nog steeds Magento 2.3 draaien voor de docker 3.0 branch

**Comment by paales** [comment]
@PascalBrouwers Officieel wordt MySQL 8.0 niet ondersteund door Magento 2.3 en de Elastic Search versie is compatible. Een reden waarom we voor 2.3 niet de oude versie zouden willen blijven gebruiken (je kan het immers per project aanpassen)?

**Comment by PascalBrouwers** [comment]
Ah ja, ik kan natuurlijk de mysql image aanpassen naar 5.7 in docker-compose.yml

**Comment by paales** [comment]
Snap niet helemaal waarom je dit zou willen? :)

**Comment by PascalBrouwers** [comment]
ah ja, ik sluit em wel. Gewoon de 2.0 branch gebruiken dan voor magento 2.3

**Comment by paales** [comment]
Ja dat is het makkelijkste inderdaad :)
