### ISSUE TITLE
Evaluate Docker 3.0 performance

### ISSUE THREAD

**Issue by paales** [ho-nl/docker-development-box#52]
https://www.docker.com/blog/docker-desktop-3-0-0-smaller-faster-releases/
https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-2500

We are currently on Docker 2.1.x.x because performance from host to container has way lower latency.

**Comment by hnsr** [comment]
Docker performance seems to be decent in current Docker releases 👌🏻
