### ISSUE TITLE
PHP 8.x Support

### ISSUE THREAD

**Issue by paales** [ho-nl/docker-development-box#57]
- [ ] Add `php` here https://github.com/ho-nl/docker-development-box/blob/master/install.sh#L4
- [ ] Move to a pecl install? https://github.com/ho-nl/docker-development-box/blob/master/install.sh#L93-L98
- [ ] Upgrade Xdebug to version 3.0 https://xdebug.org/docs/compat
- [ ] Add the correct directory for php 8.0 xdebug https://github.com/ho-nl/docker-development-box/blob/master/install.sh#L126

**Comment by hnsr** [comment]
Already implemented
