### ISSUE TITLE
Cannot use custom php file

### ISSUE THREAD

**Issue by PascalBrouwers** [ho-nl/docker-development-box#59]
@paales is er een reden dat custom php files niet gebruikt kunnen worden voor lokale development?
https://github.com/ho-nl/docker-development-box/blob/5f6cb9d3f0bfd4d68a55bfdefbbb30bd771c6d09/nginx/conf.d/default.conf#L163

**Comment by paales** [comment]
Dit komt uit de standaard nginx config https://github.com/magento/magento2/blob/2.4-develop/nginx.conf.sample#L207

**Comment by hnsr** [comment]
Closing some old issues that don't seem relevant anymore, please re-open if you still encounter this issue.
