### ISSUE TITLE
`ERR_HTTP2_PROTOCOL_ERROR` on some Magento pages

### ISSUE THREAD

**Issue by NickdeK** [ho-nl/docker-development-box#61]
On some admin configuration pages I get a `ERR_HTTP2_PROTOCOL_ERROR`. Sometimes this can be solved by clearing the cookies and doing it again, but sometimes that doesn't work.

My current workaround is to disable `web/cookie/cookie_httponly` in the Magento configuration. This seems to solve the issue for now.

**Comment by hnsr** [comment]
Closing some old issues that don't seem relevant anymore, please re-open if you still encounter this issue.
