### ISSUE TITLE
E-mail not being diverted to MailHog

### ISSUE THREAD

**Issue by hnsr** [ho-nl/docker-development-box#66]
MailHog geconfigureerd zoals in de README.md, maar lijkt niet te werken (ook niet na activeren mageplaza/module-smtp). 

Gaat in mijn geval om de 2FA activation e-mail, misschien dat dat een uitzondering is en wordt die anders verstuurd en komt de rest wel in MailHog, in welk geval dit issue wel dicht kan aangezien 2FA toch uit kan voor development.

Zal dit zelf even verifiëren als ik tijd heb.

**Comment by Maikel-Koek** [comment]
https://github.com/ho-nl/docker-development-box/pull/68

**Comment by Maikel-Koek** [comment]
Fixed by #68
