### ISSUE TITLE
Service: Imaginary

### ISSUE THREAD

**Issue by paales** [ho-nl/docker-development-box#9]

**Comment by NickdeK** [comment]
Also see #24

I do found some issues with this tho, following the instructions in the readme (and using the install.sh) I don't seem to have `pecl` available. I followed https://stackoverflow.com/questions/54521005/pecl-command-not-found-on-macbook to get this working, not sure how we can manage that in the install script.

**Comment by hnsr** [comment]
Closing some old issues that don't seem relevant anymore, please re-open if you still encounter this issue.
