### ISSUE TITLE
Remove separate 2.x branch for older Magento versions

### ISSUE THREAD

**Issue by hnsr** [ho-nl/docker-development-box#99]
Having to keep two branches up to date with `install.sh` en `README.md` changes is a bit of a hassle (or more importantly: we just forget to keep them updated). Since (I think?) the only difference between the branches is having to apply a different static content patch (depending on M2 version), I propose we just handle this by having only a main branch with the two patches in the repo with appropriate instructions in a single unified README

**Comment by PascalBrouwers** [comment]
Seems like that is the only change indeed (other than 2.x running php 7.3 by default)

**Comment by hnsr** [comment]
Removed the 2.x branch and references in the README. Existing Magento 2.3.x projects should still work
